apiVersion: v1
kind: Service
metadata:
  name: apigateway-postgresql
  labels:
{{ include "apigateway.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: apigateway-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
