# Default values for apigateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: irori.johansson.tech/automation-liberation/apigateway
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: docker-registry-credentials
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  servicePort: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-productions
  hosts:
    - host: api.johansson.tech
      paths:
        - /

  tls:
    - secretName: api-johansson-tech
      hosts:
        - api.johansson.tech

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
